### ISSUE TITLE
Dependency with CG OpenMM

### ISSUE THREAD

**Issue by tlfobe** [shirtsgroup/foldamers#34]
After our sub-group meeting on 7/2 we decided that we would like foldamers to not depend on CG OpenMM, to remove the circlular dependency of these two repos. If they both depend on each other then they would be better suited being a single repo.

To this end, let's discuss how we can go about removing the CG OpenMM dependencies in foldamers here.

**Comment by cwalker7** [comment]
I went through and found these dependencies of foldamers on CG_Openmm functions. Headers are CG_Openmm functions, and bullets are foldamers functions which depend on them: I haven't done the examples yet because a lot of them are doing both the running of the simulation and the analysis at the moment.

**build.cg_build.add_new_elements()**
- Used in cgmodel.CGModel.\_\_init\_\_

**build.cg_build.build_topology()**
- Used in cgmodel.CGModel.\_\_init\_\_
- Used in utilities.utils.get_random_positions

**build.cg_build.build_system()**
- Used in cgmodel.CGModel.\_\_init\_\_
- Used in utilities.utils.get_structure_from_library
- Used in utilities.utils.get_random_positions

**simulation.rep_exch.run_replica_exchange()**
- Used in ensembles.ens_build.get_nonnative_ensemble

**simulation.tools.minimize_structure()**
- Used in parameters.optimize.optimize_parameter
- Used in utilities.utils.get_structure_from_library
- Used in utilities.utils.get_random_positions

**simulation.tools.build_mm_simulation()**
- Used in ensembles.ens_build.get_ensemble_data
- Used in ensembles.ens_build.get_nonnative_ensemble
- Used in ensembles.ens_build.get_native_ensemble

**utilities.iotools.get_topology_from_pdbfile()**
- Used in utilities.utils.get_structure_from_library

**utilities.iotools.get_positions_from_pdbfile()**
- Used in utilities.utils.get_structure_from_library

**utilities.iotools.read_pdbfile()**
- Used in ensembles.ens_build.get_ensemble_data

**utilities.iotools.write_pdbfile_without_topology()**
- Used in ensembles.cluster.get_cluster_medoid_positions
- Used in ensembles.ens_build.write_ensemble_pdb
- Used in parameters.secondary_structure.get_helical_parameters
- Used in utilities.utils.get_structure_from_library

**Comment by cwalker7** [comment]
I think one change we could make is to move the pdb read and write functions to foldamers, since we are building the random structures in foldamers.

That brings up the question, should the random builder instead be in cg_openmm, if we want foldamers to be for strictly analysis?

**Comment by mrshirts** [comment]
OK, so let's analyze the cg_openmm functions (this is still in progress, had to stop).  A lot of the use of cg_openmm functions appears to be to remove any dependency of simtk.openmm  from foldamers.

cg_openmm 
* build.cg_build.add_new_elements() - this adds elements to the list of openmm element types, I believe so it won't get confused by having atoms that aren't elements.  The way to remove it would be to add the elements only when the OpenMM object is actually constructed.  _seems_ like this should work, would have to be tested.

* build.cg_build.build_topology() - this reads the positions from a pdb, and store the positions in the OpenMM object, and creates the openmm Topology.  It's a little weird, since it reads from a pdb that is produced earlier currently, rather than building from a pdb. Probably because it's realtively easy to create an OpenMM object from a pdb.  The cleanest way to avoid calling openmm object until a simulation is going to be run, so that the attachment of positions is done later.   However, simtk.openmm.app.pdbfile is used to read the pdb files.  I don't think we want to make our own PDB parser, so maybe we just accept that foldamers will depend on simtk.openmm.   Still trying to figure out the dependencies here, will come back.

* build.cg_build.build_system() - creates the OpenMM system.  Obviously needs OpenMM.  Needed to run a simulation, so required by any build tools that calculate energies.  Could potentially be run in a second step after the topology is created, but before the simulation is done. 

* utilities.iotools.write_pdbfile_without_topology()

I don't currently see any functions that use OpenMM here, so this would be easy to move to foldamers.  

Looking at some of the foldamer functions that use these:

* utilities.utils.get_structure_from_library. This is doing some minimization, so will require OpenMM and therefore cg_openmm.  Should this be moved to cg_openmm?

* ens_build functions.  This is actually a split between functions that _generate_ and ensemble, and those that _create_ an ensemble.  I think that this can likely be split apart into functions doing different things, will have to look more closely later.

* parameters/ functions.
   - parameters.optimize.optimize_parameter, involves calculating energies with new topologies, so probably shouldn't be there.
   -  parameters.secondary_structure.get_helical_parameters: just involved PDB writing, so would be fine if that was moved.

**Comment by cwalker7** [comment]
I think we dealt with this in the cg_openmm/foldamers merge.
